apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  namespace: go-violin-app
  labels:
    app: go-violin-pod
spec:
  containers:
    - name: go-violin-container
      image: omarsamy09/go-violin-image
      command: 
      ports:
      - containerPort: 3000
        protocol: TCP  